Asynchronous
mizukiA/chat-space pull request #5
Opened 2019-05-26 07:56 UTC by mizukiA

2019-05-26 09:01 UTC, ghost requested changes

2019-05-26 09:01 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +           <div class="upper-message__user-name">${message.user_name}</div>
したと記述が被っているところがあるので、
冗長性をなくすために、省略できるところは省略しましょう

2019-05-26 09:34 UTC, mizukiA commented
aaaaa

2019-05-26 09:39 UTC, mizukiA commented
aaa

2019-05-26 10:30 UTC, mizukiA commented on app/assets/javascripts/message.js
> +           <div class="upper-message__user-name">${message.user_name}</div>
ご確認ありがとうございます。
共通部分を別ファイルに切り出すということでしょうか？

2019-05-26 20:18 UTC, mizukiA commented on app/assets/javascripts/message.js
> +           <div class="upper-message__user-name">${message.user_name}</div>
ありがとうございます。三項演算子を使って修正しました。

2019-05-27 02:08 UTC, TOMARUMARU approved these changes
LGTM

2019-05-27 02:34 UTC, mizukiA commented
ありがとうございました。

2019-05-27 02:35 UTC, merged